import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Wrapper from "./lib/Wrapper";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "./components/Header";
import {Scroll} from 'next-animation'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "7 A",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
  <Wrapper>
    <Header />
    
        {children}
        </Wrapper>            </ThemeProvider>
      
       
        
        </body>
    </html>
  );
}
